version: '3'

services:

  qbittorrent:
    build: ./qbittorrent-pia
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - VPN_REGION=
      - VPN_USERNAME=
      - VPN_PASSWORD=
      - LAN_NETWORK=
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 8080:8080

volumes:
  qbittorrent-config:
  qbittorrent-downloads:
